// try catch block

try {
  setTimeout(() => {
    console.log("hello 1");
  }, 1000);

  setTimeout(() => {
    console.log("hello 2");
  }, 2000);

  setTimeout(() => {
    console.log("hello 3");
  }, 3000);

  setTimeout(() => {
    console.log("hello 4");
  }, 4000);

  setTimeout(() => {
    console.log("hello 4");
  }, 5000);
} catch (error) {
  console.log("error");
  
  
  console.log("hello");
  console.log(name);
  
}